README.md

I saw this by accident and decided to fix it since I was already there. 😅

Fix attribute spacing

---

.idea/misc.xml
app/src/main/java/com/bnyro/clock/obj/NumberKeypadOperation.kt
app/src/main/java/com/bnyro/clock/obj/TimeUnit.kt
app/src/main/java/com/bnyro/clock/ui/MainActivity.kt
app/src/main/java/com/bnyro/clock/ui/common/ModifierExtension.kt
app/src/main/java/com/bnyro/clock/ui/components/FormattedTimerTime.kt
app/src/main/java/com/bnyro/clock/ui/components/NumberKeypad.kt
app/src/main/java/com/bnyro/clock/ui/components/NumberPicker.kt
app/src/main/java/com/bnyro/clock/ui/components/SingleElementButton.kt
app/src/main/java/com/bnyro/clock/ui/model/TimerModel.kt
app/src/main/java/com/bnyro/clock/ui/screens/SettingsScreen.kt
app/src/main/java/com/bnyro/clock/ui/screens/TimerScreen.kt
app/src/main/java/com/bnyro/clock/ui/theme/Type.kt
app/src/main/java/com/bnyro/clock/util/Preferences.kt
app/src/main/res/values/strings.xml

Hey @Bnyro,
I'm not sure if you remember me, but I asked you on Matrix how you started with Kotlin development and what you would beginners on what to do - well I followed your advice and here's my first contribution to an open source project! :D Because it's my first time writing Kotlin code for production, please make sure to pay special attention, as there are probably a lot of things that can be improved with this code.
I added a better timer setup - There's now a number keypad, like in the Google Clock app.
Here's a preview of it:
[out.webm](https://github.com/Bnyro/ClockYou/assets/50424412/074f543c-ac13-4045-818f-6466f0d12ae8)

Add number keypad

---

app/src/main/java/com/bnyro/clock/ui/model/TimerModel.kt

Fix timer picker

---

app/src/main/java/com/bnyro/clock/obj/ScheduledObject.kt
app/src/main/java/com/bnyro/clock/ui/screens/TimerScreen.kt

Add timer progress bars

---

app/src/main/java/com/bnyro/clock/ui/nav/NavContainer.kt
app/src/main/java/com/bnyro/clock/ui/nav/NavHost.kt
app/src/main/java/com/bnyro/clock/ui/nav/NavRoutes.kt

Also reordered the tabs in all files for consistency.

Start on alarm tab (closes #128)

---

app/build.gradle.kts
app/src/main/java/com/bnyro/clock/ui/model/ClockModel.kt
app/src/main/java/com/bnyro/clock/ui/screens/ClockScreen.kt
app/src/main/java/com/bnyro/clock/util/TimeHelper.kt
gradle/libs.versions.toml

fix: displayed time for different regions and their offset

---

app/src/main/java/com/bnyro/clock/ui/dialog/RingtonePickerDialog.kt
app/src/main/java/com/bnyro/clock/util/RingtoneHelper.kt

feat: possibility to listen to ringtone before applying it

---

fastlane/metadata/android/en-US/changelogs/11.txt

I guessed next release will have versionCode `12` :shrug:

Add changelog

---

app/src/main/java/com/bnyro/clock/util/TimeHelper.kt

fix: hide seconds in 12 hour clock

---

app/src/main/java/com/bnyro/clock/ui/screens/StopwatchScreen.kt

closes #178
Not sure if that's really a good solution, screenshots below:

refactor: use large rounde FAB for major stopwatch actions

---

app/src/main/java/com/bnyro/clock/ui/nav/NavContainer.kt
app/src/main/java/com/bnyro/clock/ui/nav/NavHost.kt
app/src/main/java/com/bnyro/clock/ui/nav/TopBarScaffold.kt
app/src/main/java/com/bnyro/clock/ui/screens/AlarmScreen.kt
app/src/main/java/com/bnyro/clock/ui/screens/ClockScreen.kt
app/src/main/java/com/bnyro/clock/ui/screens/SettingsScreen.kt
app/src/main/java/com/bnyro/clock/ui/screens/StopwatchScreen.kt
app/src/main/java/com/bnyro/clock/ui/screens/TimerScreen.kt

fix: Layout shifts when opening settings

---

.idea/inspectionProfiles/Project_Default.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/bnyro/clock/receivers/AlarmReceiver.kt
app/src/main/java/com/bnyro/clock/services/AlarmService.kt
app/src/main/java/com/bnyro/clock/ui/AlarmActivity.kt
app/src/main/java/com/bnyro/clock/ui/screens/AlarmAlertScreen.kt
app/src/main/java/com/bnyro/clock/util/AlarmHelper.kt
app/src/main/java/com/bnyro/clock/util/NotificationHelper.kt
app/src/main/java/com/bnyro/clock/util/Preferences.kt
app/src/main/res/values/strings.xml

Features:
- Full screen alarm notification with dismiss button
- Turn on the screen automatically
- Shows even when the screen is locked
TODO:
- Auto dismiss alarm after some time
- add dismiss buttons to the notification

feat: add full screen intent for alarm

---

app/src/main/java/com/bnyro/clock/services/AlarmService.kt
app/src/main/java/com/bnyro/clock/util/NotificationHelper.kt

Silent any notification sounds for the alarm notification

---

app/src/main/java/com/bnyro/clock/ui/components/AlarmRow.kt
app/src/main/java/com/bnyro/clock/util/TimeHelper.kt

fix: alarm time not respecting locale

---

app/src/main/java/com/bnyro/clock/ui/screens/ClockScreen.kt
app/src/main/java/com/bnyro/clock/util/TimeHelper.kt
app/src/main/res/values/strings.xml

feat: show how many hours each time zone is ahead or behind

---

app/src/main/java/com/bnyro/clock/ui/components/AlarmRow.kt
app/src/main/java/com/bnyro/clock/util/AlarmHelper.kt

feat: respect system first day of week for alarms

---

app/src/main/java/com/bnyro/clock/util/TimeHelper.kt

feat: show day of the week in clock screen

---

app/src/main/java/com/bnyro/clock/ui/model/ClockModel.kt
app/src/main/java/com/bnyro/clock/ui/screens/ClockScreen.kt
app/src/main/java/com/bnyro/clock/util/TimeHelper.kt
app/src/main/res/values/strings.xml

| Before | After |
| --- | --- |
|![image](https://github.com/you-apps/ClockYou/assets/64766434/c3f867f9-a71f-4da5-9b10-df2edd9a609e) | ![image](https://github.com/you-apps/ClockYou/assets/64766434/0faef1ef-acd5-4b7c-8948-dff5d71f73a0) |

style: improved clock screen design

---

app/src/main/java/com/bnyro/clock/ui/screens/StopwatchScreen.kt

https://github.com/you-apps/ClockYou/assets/64766434/c13453eb-f407-4a9f-8533-b4c133fdb855

style: add progress ring for stopwatch

---

app/src/main/AndroidManifest.xml

fix #231
This might not be the best solution. But it's definitely the easiest.

fix: app crash on boot

---

app/src/main/java/com/bnyro/clock/ui/components/AlarmSettingsSheet.kt
app/src/main/java/com/bnyro/clock/util/AlarmHelper.kt

Relative time strings will now respect the day of the week setting
closes #241

feat: improved alarm relative time display

---

app/src/main/java/com/bnyro/clock/ui/MainActivity.kt
app/src/main/java/com/bnyro/clock/ui/components/AlarmSettingsSheet.kt
app/src/main/java/com/bnyro/clock/ui/dialog/AlarmReceiverDialog.kt
app/src/main/java/com/bnyro/clock/ui/screens/AlarmScreen.kt

https://github.com/you-apps/ClockYou/assets/64766434/8f4b40c7-a24f-46bc-81c0-3f7bf46d9c3d

feat: better alarm receiver dialog

---

app/build.gradle.kts
app/schemas/com.bnyro.clock.db.AppDatabase/7.json
app/src/main/assets/tz_data.json
app/src/main/java/com/bnyro/clock/db/AppDatabase.kt
app/src/main/java/com/bnyro/clock/obj/CountryTimezone.kt
app/src/main/java/com/bnyro/clock/obj/TimeZone.kt
app/src/main/java/com/bnyro/clock/ui/model/ClockModel.kt
app/src/main/java/com/bnyro/clock/ui/nav/NavContainer.kt
app/src/main/java/com/bnyro/clock/ui/screens/ClockScreen.kt
app/src/main/java/com/bnyro/clock/util/TimeHelper.kt
app/src/main/java/com/bnyro/clock/util/TimezoneHelper.kt
gradle/libs.versions.toml

feat: use country names for timezones

---

app/src/main/java/com/bnyro/clock/ui/MainActivity.kt
app/src/main/java/com/bnyro/clock/ui/model/SettingsModel.kt
app/src/main/java/com/bnyro/clock/ui/prefs/ColorPref.kt
app/src/main/java/com/bnyro/clock/ui/screens/AlarmAlertScreen.kt
app/src/main/java/com/bnyro/clock/ui/screens/SettingsScreen.kt
app/src/main/java/com/bnyro/clock/ui/theme/Theme.kt
app/src/main/java/com/bnyro/clock/util/Preferences.kt
app/src/main/java/com/bnyro/clock/util/ThemeUtil.kt
app/src/main/res/values/strings.xml

https://github.com/you-apps/ClockYou/assets/64766434/002a0eae-3830-493e-9cfb-2061e770fb7d

feat: custom themes

---

app/src/main/java/com/bnyro/clock/services/AlarmService.kt

feat: auto stop alarm after 10 minutes

---

app/src/main/java/com/bnyro/clock/ui/components/AlarmRow.kt
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml

This is a little feature that I really missed from the aosp clock that I think improves clarity when enabling an alarm.

Added a Toast notification when enabling an alarm

---

app/src/main/java/com/bnyro/clock/db/dao/AlarmsDao.kt
app/src/main/java/com/bnyro/clock/ui/components/AlarmRow.kt
app/src/main/java/com/bnyro/clock/ui/screens/AlarmScreen.kt

fix: wrong alarm shown as enabled after deleting previous one

---

app/src/main/java/com/bnyro/clock/ui/MainActivity.kt
app/src/main/java/com/bnyro/clock/ui/nav/NavContainer.kt
app/src/main/java/com/bnyro/clock/ui/screens/SettingsScreen.kt
app/src/main/java/com/bnyro/clock/util/Preferences.kt
app/src/main/res/values/strings.xml

feat: option to set custom start tab

---

app/src/main/java/com/bnyro/clock/obj/AlarmFilters.kt
app/src/main/java/com/bnyro/clock/ui/components/AlarmFilterSection.kt
app/src/main/java/com/bnyro/clock/ui/model/AlarmModel.kt
app/src/main/java/com/bnyro/clock/ui/screens/AlarmScreen.kt
app/src/main/res/values/strings.xml

Adding the option to filter the alarms 
https://github.com/you-apps/ClockYou/assets/155833069/58c356cc-4fce-46fc-bdf0-3ae8d229b232

feat: add option for filtering alarms

---

app/src/main/java/com/bnyro/clock/ui/AlarmActivity.kt

feat: press volume down to snooze an alarm

---

app/schemas/com.bnyro.clock.db.AppDatabase/8.json
app/src/main/java/com/bnyro/clock/db/AppDatabase.kt
app/src/main/java/com/bnyro/clock/db/DatabaseHolder.kt
app/src/main/java/com/bnyro/clock/obj/TimeZone.kt
app/src/main/java/com/bnyro/clock/ui/model/ClockModel.kt
app/src/main/java/com/bnyro/clock/ui/screens/ClockScreen.kt
app/src/main/java/com/bnyro/clock/util/TimeHelper.kt

fix: crash when two time zone regions have the same name

---

app/src/main/java/com/bnyro/clock/obj/Alarm.kt
app/src/main/java/com/bnyro/clock/ui/components/AlarmRow.kt
app/src/main/java/com/bnyro/clock/ui/model/AlarmModel.kt

https://github.com/you-apps/ClockYou/assets/64766434/f35ecc56-1789-4c73-acf0-6161a3a89386

feat: search alarm by time

---

app/src/main/java/com/bnyro/clock/obj/ScheduledObject.kt
app/src/main/java/com/bnyro/clock/services/TimerService.kt
app/src/main/java/com/bnyro/clock/ui/components/TimerItem.kt
app/src/main/java/com/bnyro/clock/ui/dialog/RingtonePickerDialog.kt

feat(timer): support for vibrating when finished

---

app/src/main/java/com/bnyro/clock/obj/TimeObject.kt
app/src/main/java/com/bnyro/clock/ui/model/StopwatchModel.kt
app/src/main/java/com/bnyro/clock/ui/nav/NavContainer.kt
app/src/main/java/com/bnyro/clock/ui/screens/StopwatchScreen.kt
app/src/main/res/values/strings.xml

feat: show the time between laps

---

app/src/main/java/com/bnyro/clock/ui/MainActivity.kt
app/src/main/java/com/bnyro/clock/ui/nav/NavContainer.kt
app/src/main/java/com/bnyro/clock/ui/nav/NavHost.kt

Fix: Annoying tab switching behaviour

---

app/src/main/java/com/bnyro/clock/domain/usecase/CreateUpdateDeleteAlarmUseCase.kt
app/src/main/java/com/bnyro/clock/presentation/screens/alarmpicker/AlarmPickerScreen.kt

feat: auto enable alarms when updating
